language: php
php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm
matrix:
  allow_failures:
    - php: hhvm
before_script:
  # Composer
  - composer --no-interaction self-update
  - composer --no-interaction --prefer-source --dev install
script:
  # Code style
  - php vendor/bin/phpcs --standard=./phpcs.xml --encoding=utf-8 ./app ./lib ./shell
